#!/bin/bash
# Quick Setup Guide for Infinity Motors Backend

echo "🚀 Infinity Motors Backend - Setup Instructions"
echo "=============================================="
echo ""

echo "✅ Backend Created Successfully!"
echo ""
echo "📁 Backend Structure:"
echo "  backend/"
echo "  ├── server.js                    (Main Express server)"
echo "  ├── package.json                 (Dependencies: Express, JWT, bcrypt, validators)"
echo "  ├── .env.example                 (Environment template)"
echo "  ├── AUTHENTICATION.md            (Complete auth guide)"
echo "  ├── README.md                    (Original documentation)"
echo "  ├── controllers/"
echo "  │   └── authController.js        (Login with validation & rate limiting)"
echo "  ├── routes/"
echo "  │   └── auth.js                  (Auth endpoints)"
echo "  ├── middleware/"
echo "  │   ├── auth.js                  (JWT verification)"
echo "  │   ├── validators.js            (Input validation rules)"
echo "  │   └── rateLimiter.js           (Rate limiting: 5 attempts/15min)"
echo "  ├── models/"
echo "  │   └── User.js                  (User schema with bcrypt)"
echo "  └── utils/"
echo "      └── validation.js            (Validation utilities)"
echo ""

echo "⚙️  SETUP STEPS:"
echo "1. Navigate to backend:"
echo "   cd backend"
echo ""
echo "2. Install dependencies:"
echo "   npm install"
echo ""
echo "3. Create .env file:"
echo "   cp .env.example .env"
echo ""
echo "4. Update .env with your values:"
echo "   - MONGODB_URI=mongodb://localhost:27017/infinity-motors"
echo "   - JWT_SECRET=your_secret_key"
echo "   - PORT=5000"
echo ""
echo "5. Start MongoDB (if not running)"
echo ""
echo "6. Run the server:"
echo "   npm run dev        (Development with auto-reload)"
echo "   npm start          (Production)"
echo ""

echo "✨ NEW FEATURES ADDED:"
echo "  ✓ Login validation with express-validator"
echo "  ✓ Rate limiting (5 attempts per 15 minutes)"
echo "  ✓ Account lockout after failed attempts"
echo "  ✓ Password strength validation"
echo "  ✓ Bcrypt password hashing (salt rounds: 10)"
echo "  ✓ JWT authentication with token expiration"
echo "  ✓ Security headers (XSS, clickjacking protection)"
echo "  ✓ Comprehensive error handling"
echo ""

echo "📝 VALIDATION RULES:"
echo "  Login Email:"
echo "    - Required"
echo "    - Must be valid email format"
echo "    - Case-insensitive"
echo ""
echo "  Login Password:"
echo "    - Required"
echo "    - Min 6 characters"
echo "    - Compared securely with bcrypt"
echo ""
echo "  Registration Password:"
echo "    - Min 6 characters in form"
echo "    - But must be STRONG to register:"
echo "      • Uppercase letters (A-Z)"
echo "      • Lowercase letters (a-z)"
echo "      • Numbers (0-9)"
echo "      • Min 8 characters"
echo ""

echo "🔑 API ENDPOINTS:"
echo ""
echo "  PUBLIC:"
echo "  POST   /api/auth/register              (Register new user)"
echo "  POST   /api/auth/login                 (Login - rate limited)"
echo ""
echo "  PROTECTED (need Authorization header):"
echo "  GET    /api/auth/me                    (Get current user)"
echo "  PUT    /api/auth/profile               (Update profile)"
echo "  PUT    /api/auth/change-password       (Change password)"
echo ""

echo "📚 DOCUMENTATION:"
echo "  - Read: backend/AUTHENTICATION.md      (Complete auth guide)"
echo "  - Read: backend/README.md              (API documentation)"
echo ""

echo "🔐 SECURITY FEATURES:"
echo "  ✓ Brute force protection (account lockout)"
echo "  ✓ Strong password requirements"
echo "  ✓ Bcryptjs hashing"
echo "  ✓ JWT token validation"
echo "  ✓ CORS protection"
echo "  ✓ Security headers"
echo "  ✓ Input validation & sanitization"
echo ""

echo "🧪 TEST THE API:"
echo ""
echo "1. Register:"
echo "   curl -X POST http://localhost:5000/api/auth/register \\"
echo "   -H \"Content-Type: application/json\" \\"
echo "   -d '{\"name\":\"John\",\"email\":\"john@test.com\",\"password\":\"SecurePass123!\"}'"
echo ""
echo "2. Login:"
echo "   curl -X POST http://localhost:5000/api/auth/login \\"
echo "   -H \"Content-Type: application/json\" \\"
echo "   -d '{\"email\":\"john@test.com\",\"password\":\"SecurePass123!\"}'"
echo ""
echo "3. Get User (replace TOKEN with actual JWT):"
echo "   curl -X GET http://localhost:5000/api/auth/me \\"
echo "   -H \"Authorization: Bearer YOUR_TOKEN_HERE\""
echo ""

echo "❓ COMMON ISSUES:"
echo "  Q: How long is account locked?"
echo "  A: 15 minutes after 5 failed attempts"
echo ""
echo "  Q: What makes a password strong?"
echo "  A: Uppercase + Lowercase + Number + 8+ characters"
echo ""
echo "  Q: How long do tokens last?"
echo "  A: 7 days by default (set JWT_EXPIRE in .env)"
echo ""

echo "✅ Ready to start! Run: cd backend && npm run dev"
